/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace CDJNFSLibrary.Protocols.V4.RPC
{
    using org.acplt.oncrpc;

    public class clientaddr4 : XdrAble
    {
        public netaddr4 value;

        public clientaddr4()
        {
        }

        public clientaddr4(netaddr4 value)
        {
            this.value = value;
        }

        public clientaddr4(XdrDecodingStream xdr)
        {
            xdrDecode(xdr);
        }

        public void xdrEncode(XdrEncodingStream xdr)
        {
            value.xdrEncode(xdr);
        }

        public void xdrDecode(XdrDecodingStream xdr)
        {
            value = new netaddr4(xdr);
        }
    }
} // End of clientaddr4.cs