/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace CDJNFSLibrary.Protocols.V4.RPC
{
    /**
     * Enumeration (collection of constants).
     */

    public class limit_by4
    {
        public const int NFS_LIMIT_SIZE = 1;
        public const int NFS_LIMIT_BLOCKS = 2;
    }
}

// End of limit_by4.cs