/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace CDJNFSLibrary.Protocols.V4.RPC
{
    using org.acplt.oncrpc;

    public class OPEN_CONFIRM4args : XdrAble
    {
        public stateid4 open_stateid;
        public seqid4 seqid;

        public OPEN_CONFIRM4args()
        {
        }

        public OPEN_CONFIRM4args(XdrDecodingStream xdr)
        {
            xdrDecode(xdr);
        }

        public void xdrEncode(XdrEncodingStream xdr)
        {
            seqid.xdrEncode(xdr);
        }

        public void xdrDecode(XdrDecodingStream xdr)
        {
            seqid = new seqid4(xdr);
        }
    }
} // End of OPEN_CONFIRM4args.cs