/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace CDJNFSLibrary.Protocols.V4.RPC
{
    /**
     * Enumeration (collection of constants).
     */

    public class secinfo_style4
    {
        public const int SECINFO_STYLE4_CURRENT_FH = 0;
        public const int SECINFO_STYLE4_PARENT = 1;
    }
} // End of secinfo_style4.cs