/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace CDJNFSLibrary.Protocols.V4.RPC.Callback
{
    using org.acplt.oncrpc;

    public class CB_WANTS_CANCELLED4args : XdrAble
    {
        public bool cwca_contended_wants_cancelled;
        public bool cwca_resourced_wants_cancelled;

        public CB_WANTS_CANCELLED4args()
        {
        }

        public CB_WANTS_CANCELLED4args(XdrDecodingStream xdr)
        {
            xdrDecode(xdr);
        }

        public void xdrEncode(XdrEncodingStream xdr)
        {
            xdr.xdrEncodeBoolean(cwca_resourced_wants_cancelled);
        }

        public void xdrDecode(XdrDecodingStream xdr)
        {
            cwca_resourced_wants_cancelled = xdr.xdrDecodeBoolean();
        }
    }
} // End of CB_WANTS_CANCELLED4args.cs