/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace CDJNFSLibrary.Protocols.V4.RPC.Callback
{
    /**
     * Enumeration (collection of constants).
     */

    public class layoutrecall_type4
    {
        private const int LAYOUT4_RET_REC_FILE = 1;
        private const int LAYOUT4_RET_REC_FSID = 2;
        private const int LAYOUT4_RET_REC_ALL = 3;

        public const int LAYOUTRECALL4_FILE = LAYOUT4_RET_REC_FILE;
        public const int LAYOUTRECALL4_FSID = LAYOUT4_RET_REC_FSID;
        public const int LAYOUTRECALL4_ALL = LAYOUT4_RET_REC_ALL;
    }
} // End of layoutrecall_type4.cs