/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace RekordboxNFSLibrary.Protocols.V4.RPC
{
    /**
     * Enumeration (collection of constants).
     */

    public class filelayout_hint_care4
    {
        public const int NFLH4_CARE_DENSE = NFSv4Protocol.NFL4_UFLG_DENSE;
        public const int NFLH4_CARE_COMMIT_THRU_MDS = NFSv4Protocol.NFL4_UFLG_COMMIT_THRU_MDS;
        public const int NFLH4_CARE_STRIPE_UNIT_SIZE = 0x00000040;
        public const int NFLH4_CARE_STRIPE_COUNT = 0x00000080;
    }
} // End of  filelayout_hint_care4.cs